version: '3.1'

networks:
  qa:
    driver: bridge

services:
  s3:
    container_name: qa_s3
    image: minio/minio:RELEASE.2022-10-29T06-21-33Z
    command:
      server --console-address :9001 /data
    expose:
      - "9000"
    ports:
      - "9900:9000"
      - "9901:9001"
    environment:
      - MINIO_ACCESS_KEY=s3_access_key
      - MINIO_SECRET_KEY=s3_secret_key
    volumes:
      - s3:/data
    networks:
      - qa

  emb_serving:
    container_name: qa_emb_serving
    image: emb_serving:0.1
    expose:
      - "8000"
    networks:
      - qa

  api_gateway:
    container_name: qa_api-gateway
    image: api-gateway:0.1
    ports:
      - "9910:8000"
    environment:
      - EMB_SERVING_URL=emb_serving
      - EMB_SERVING_PORT=8000
    networks:
      - qa

  cluster1:
    container_name: qa_cluster1
    image: cluster_node:0.1
    depends_on:
      - s3
    expose:
      - "8000"
    environment:
      - DATA_GENERATION=1
      - CLUSTER_ID=0
      - S3_URL=s3:9000
      - S3_ACCESS_KEY=s3_access_key
      - S3_SECRET_KEY=s3_secret_key
    networks:
      - qa

  cluster2:
    container_name: qa_cluster2
    image: cluster_node:0.1
    depends_on:
      - s3
    expose:
      - "8000"
    environment:
      - DATA_GENERATION=1
      - CLUSTER_ID=1
      - S3_URL=s3:9000
      - S3_ACCESS_KEY=s3_access_key
      - S3_SECRET_KEY=s3_secret_key
    networks:
      - qa

  cluster3:
    container_name: qa_cluster3
    image: cluster_node:0.1
    depends_on:
      - s3
    expose:
      - "8000"
    environment:
      - DATA_GENERATION=1
      - CLUSTER_ID=2
      - S3_URL=s3:9000
      - S3_ACCESS_KEY=s3_access_key
      - S3_SECRET_KEY=s3_secret_key
    networks:
      - qa

  cluster4:
    container_name: qa_cluster4
    image: cluster_node:0.1
    depends_on:
      - s3
    expose:
      - "8000"
    environment:
      - DATA_GENERATION=1
      - CLUSTER_ID=3
      - S3_URL=s3:9000
      - S3_ACCESS_KEY=s3_access_key
      - S3_SECRET_KEY=s3_secret_key
    networks:
      - qa


volumes:
  s3: